---
name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    uses: wetransform/gha-workflows/.github/workflows/gradle-library-check.yml@11ac55c836e622b4a3c944e057f9067cfdc6ab11 # v4.1.1
    with:
      java-version: 17
      multi-module: false
      skip-scan: true
