---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Check

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    uses: wetransform/gha-workflows/.github/workflows/dockerfile-build.yml@11ac55c836e622b4a3c944e057f9067cfdc6ab11 # v4.1.1
    with:
      image: wetransform/conversion-gdal
      tag: pr
