---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Check

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    uses: wetransform/gha-workflows/.github/workflows/dockerfile-build.yml@2740e518e1d9ea2e965a901281e051ea26e3512c # v4.1.0
    with:
      image: wetransform/conversion-gdal
      tag: pr
