---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Check

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    uses: wetransform/gha-workflows/.github/workflows/dockerfile-build.yml@c00295d992672213a1da3e7d06543e668290a97e # v4.2.0
    with:
      image: wetransform/conversion-gdal
      tag: pr
